const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./endpoints.js"];

const doc = {
    info: {
        version: "1.0.0",
        title: "APIGames API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
});
